version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "build:"
    open-pull-requests-limit: 4