version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: "build:"
    groups:
      spring-boot-dependencies:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework.data:*"
      spring-dependencies:
        patterns:
          - "org.springframework*"
        exclude-patterns:
          - "org.springframework.boot:*"
          - "org.springframework.data:*"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
    open-pull-requests-limit: 9