name: (Manual) Run tests for EMEA instance

on:
  workflow_dispatch:
    inputs:
      specsDir:
        description: 'Gauge specs dir'
        required: true
        type: choice
        options:
          - 'all'
          - 'specs/2fm/tests/lee/audi'
          - 'specs/2fm/tests/lee/audikr'
          - 'specs/2fm/tests/lee/seat'
          - 'specs/2fm/tests/lee/skoda'
          - 'specs/2fm/tests/lee/vw'
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: true
        options:
          - 'mod4-dev'
          - 'mod4-sandbox'
          - 'mod4-prod'

jobs:
  decode:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: decode
        uses: ./.github/actions/decode
        with:
          trustedClientCertificateBase64: ${{ secrets.TRUSTED_CLIENT_CERTIFICATE_BASE64 }}
          trustedClientCertificateOuterPassword: ${{ secrets.TRUSTED_CLIENT_CERTIFICATE_OUTER_PASSWORD }}